on:
  push:
    branches: ['main']

jobs:
  build-docker-image:
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: 'actions/checkout@v4'

      - name: 'Set Up JDK 17'
        uses: 'actions/setup-java@v4'
        with:
          distribution: 'corretto'
          java-version: 17

      - name: 'Setup Gradle'
        uses: 'gradle/actions/setup-gradle@v4'

      - name: 'Build with Gradle'
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: 'Set short SHA'
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: 'Print SHORT_SHA'
        run: echo "Short SHA is $SHORT_SHA"

      - name: 'Login to DockerHub'
        uses: 'docker/login-action@v1'
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: 'DockerHub Upload'
        id: 'build-image'
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME}}
          DOCKER_HUB_REPOSITORY: 'gitops-2024-service'
        run: |
          docker build -t $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:$SHORT_SHA .
          docker push $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:$SHORT_SHA
          echo "image=$DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: 'Checkout Helm Chart Repository'
        uses: 'actions/checkout@v4'
        with:
          repository: 'yelimkim98/gitops-2024-helm'
          token: ${{ secrets.HELM_ACCESS_TOKEN }}
          # path :
          # helm-chart 디렉토리에 체크아웃된 파일을 저장하겠다고 지정
          # 즉, kiel0103/gitops-2024-helm 저장소의 내용이
          # helm-chart/ 디렉토리로 복사되게 된다.
          path: 'helm-chart'
          ref: 'main'

      - name: 'Update Helm Chart Values'
        # helm-chart/values.yaml 파일에서
        # repository:로 시작하는 줄을 찾아서 (앞에 띄어쓰기 있어도 찾아짐)
        # repository: kiel0103/gitops-2024-service:$SHORT_SHA 로 수정
        run: |
          sed -i "s|repository:.*|repository: kiel0103/gitops-2024-service:$SHORT_SHA|g" helm-chart/values.yaml

      - name: 'Commit and Push Updated Helm Chart'
        run: |
          cd helm-chart
          git config user.name "yelimkim98"
          git config user.email "kiel0103@naver.com"
          git add values.yaml
          git commit -m "Update image tag to $SHORT_SHA"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.HELM_ACCESS_TOKEN }}
